spring.application.name=user-service
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/${POSTGRES_DB:observability_db}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER:postgres}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD:postgres}}
logging.level.com.observability.userservice=INFO
users.pagination.max-size=50
